### ISSUE TITLE
Strange output

### ISSUE THREAD

**Issue by alexanderilyin** [verkkokauppacom/parallel-phpunit#1]
It will be nice to have same output as original phpunit have. Right now I see something strange:

```
$ bin/parallel-phpunit example/
Running parallel wrapper for phpunit
Starting command: phpunit   example//1
Starting command: phpunit   example//2
Starting command: phpunit   example//5/6
Success: 1 Fail: 0 Error: 0 Skip: 0 Incomplete: 0
Command ended: phpunit   example//5/6
Command ended: phpunit   example//1
PHPUnit @package_version@ by Sebastian Bergmann.

.

Time: 2 seconds, Memory: 5.00Mb

OK (1 test, 1 assertion)
PHPUnit @package_version@ by Sebastian Bergmann.

.

Time: 2 seconds, Memory: 5.00Mb

OK (1 test, 1 assertion)
Command ended: phpunit   example//2
PHPUnit @package_version@ by Sebastian Bergmann.

...

Time: 3 seconds, Memory: 5.25Mb

OK (3 tests, 3 assertions)
Success: 5 Fail: 0 Error: 0 Skip: 0 Incomplete: 0

```

**Comment by siivonen** [comment]
You see three parallel phpunit outputs plus their start and end commands plus the summary lines. It takes a bit of time to learn how to read the output. Changing this output the standard phpunit output would be much easier to read at first but you will also lose these:

 # Information which parallel phpunit commands are running
 # Instant feedback of failing or successful phpunit commands (no need to wait all the commands to end)
 # The total number of test ran so far

I wouldn't want to lose any of these. Also achieving parallel "real-time crowing dots" would be very hard to achieve naturally with Bash since it is so tightly fixed to line buffering (= you would see the dots crowing only line by line, not character by character).

**Comment by alexanderilyin** [comment]
It will be possible to do "real-time crowing dots" by using custom `--printer` option like this one: [--option PHPUnit_Extensions_TeamCity_TestListener](https://github.com/badoo/phpunit-testlistener-teamcity/blob/master/Extensions/TeamCity/TestListener.php) — it will allow to print output in format which will be parsed by shell script form each process and then print common progress. Will you try implement this?

**Comment by siivonen** [comment]
Ok, I will try when I have the time. I'll get back on this.

**Comment by siivonen** [comment]
I started to implement this at some point but the solution got pretty complex compared to the gain. Now release 1.1 introduced the --pu-threads switch which limits the number of threads running at the same time. After that I think it's even more important to print the starting and ending the of the command executions which anyway mess up the traditional progress dot output.

For these reasons I decided to not to implement this at all. Sorry!
