### ISSUE TITLE
parallel-phpunit doesn't recognize php errors

### ISSUE THREAD

**Issue by tomi20v** [verkkokauppacom/parallel-phpunit#12]
I've been running some tests but it seems parallel-phpunit just runs fine, without reporting any errors, if there is a php error. Look at the log excerpt I've attached.

(...)
Success: 0 Fail: 0 Error: 0 Skip: 0 Incomplete: 0
Command ended: /usr/bin/phpunit -d parallel-phpunit-thread=1  ./b3Test.php
PHPUnit 3.7.21 by Sebastian Bergmann.

PHP Fatal error:  Call to undefined function fuckItUp() in /var/www/t/b/b3Test.php on line 54
PHP Stack trace:
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:176
PHP   5. PHPUnit_Framework_TestSuite->run() /usr/share/php/PHPUnit/TextUI/TestRunner.php:349
PHP   6. PHPUnit_Framework_TestSuite->runTest() /usr/share/php/PHPUnit/Framework/TestSuite.php:745
PHP   7. PHPUnit_Framework_TestCase->run() /usr/share/php/PHPUnit/Framework/TestSuite.php:775
PHP   8. PHPUnit_Framework_TestResult->run() /usr/share/php/PHPUnit/Framework/TestCase.php:776
PHP   9. PHPUnit_Framework_TestCase->runBare() /usr/share/php/PHPUnit/Framework/TestResult.php:648
PHP  10. PHPUnit_Framework_TestCase->runTest() /usr/share/php/PHPUnit/Framework/TestCase.php:831
PHP  11. ReflectionMethod->invokeArgs() /usr/share/php/PHPUnit/Framework/TestCase.php:976
PHP  12. b3Test->test1() /usr/share/php/PHPUnit/Framework/TestCase.php:976
Starting command with thread 1: /usr/bin/phpunit -d parallel-phpunit-thread=1  ./b2Test.php
./b5Test.php
Success: 1 Fail: 0 Error: 0 Skip: 0 Incomplete: 0
Success: 1 Fail: 0 Error: 0 Skip: 0 Incomplete: 0
Success: 1 Fail: 0 Error: 0 Skip: 0 Incomplete: 0
(...)

**Comment by siivonen** [comment]
I couldn't reproduce this error. When an individual phpunit command throws a php error, a stack trace is printed out and the whole parallel-phpunit command will fail when it is finished. The test that throws php error is not counted to the status lines at all. I guess that in your example run the 'Success: 1' value is caused by some other, concurrently running test that has successfully ran one test but is still running another one. The status lines are counted from the outputs of all running and finished test runs so you will see the number of successfull/failing tests even though you don't see the outputs in the log yet.

Here is how I tested this:
1. Go to parallel-phpunit checkout root
2. Modify example/2/BTest.php (call to undefined method)
3. Run './bin/parallel-phpunit example/2/ || echo "Command failed"'
   
   Running parallel-phpunit 1.2
   Starting command with thread 0: /usr/bin/phpunit -d parallel-phpunit-thread=0  example/2/BTest.php
   Starting command with thread 1: /usr/bin/phpunit -d parallel-phpunit-thread=1  example/2/4/DTest.php
   Command ended: /usr/bin/bin/phpunit -d parallel-phpunit-thread=0  example/2/BTest.php
   PHPUnit 3.7.21 by Sebastian Bergmann.
   
   PHP Fatal error:  Call to undefined method BTest::fuckItUp() in /home/siivonen/parallel-phpunit/example/2/BTest.php on line 9
   PHP Stack trace:
   PHP   1. {main}() /Users/samulisiivonen/verkkokauppa.com/verkkokauppa/vendor/phpunit/phpunit/composer/bin/phpunit:0
   PHP   2. PHPUnit_TextUI_Command::main()  /usr/bin/phpunit:63
   PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
   PHP   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:176
   PHP   5. PHPUnit_Framework_TestSuite->run() /usr/share/php/PHPUnit/TextUI/TestRunner.php:349
   PHP   6. PHPUnit_Framework_TestSuite->runTest() /usr/share/php/PHPUnit/Framework/TestSuite.php:745
   PHP   7. PHPUnit_Framework_TestCase->run() /usr/share/php/PHPUnit/Framework/TestSuite.php:775
   PHP   8. PHPUnit_Framework_TestResult->run() /usr/share/php/PHPUnit/Framework/TestCase.php:776
   PHP   9. PHPUnit_Framework_TestCase->runBare() /usr/share/php/PHPUnit/Framework/TestResult.php:648
   PHP  10. PHPUnit_Framework_TestCase->runTest() /usr/share/php/PHPUnit/Framework/TestCase.php:831
   PHP  11. ReflectionMethod->invokeArgs() /usr/share/php/PHPUnit/Framework/TestCase.php:976
   PHP  12. BTest->testIt() /usr/share/php/PHPUnit/Framework/TestCase.php:976
   Starting command with thread 0: /usr/bin/phpunit -d parallel-phpunit-thread=0  example/2/3/CTest.php
   Command ended: /usr/bin/phpunit -d parallel-phpunit-thread=1  example/2/4/DTest.php
   PHPUnit 3.7.21 by Sebastian Bergmann    .
   
   .
   
   Time: 1 second, Memory: 5.25Mb
   
   OK (1 test, 1 assertion)
   Command ended:/usr/bin/phpunit -d parallel-phpunit-thread=0  example/2/3/CTest.php
   PHPUnit 3.7.21 by Sebastian Bergmann.
   
   .
   
   Time: 1 second, Memory: 5.25Mb    
   
   OK (1 test, 1 assertion)
   Success: 2 Fail: 0 Error: 0 Skip: 0 Incomplete: 0
   Command failed

If you still think that there is an issue to be fixed could you give me instructions on how to reproduce the problem with parallel-phpunit example tests?

**Comment by razielsd** [comment]
When fatal error php return exit code  more zero. Example:

```
#!/bin/bash
razielsd@razielsd-vm:~/projects/tmp$ cat ./fatal.sh
#!/bin/bash
php -r 'Fatal::show()'
echo "Exit code: $?"
razielsd@razielsd-vm:~/projects/tmp$ ./fatal.sh
PHP Parse error:  syntax error, unexpected end of file in Command line code on line 1

Parse error: syntax error, unexpected end of file in Command line code on line 1
Exit code: 254
```

You can check fail exit code and show error message. Example in my version parallel-phpunit: https://github.com/razielsd/parallel-phpunit2/blob/master/lib/Core/Runner.php#L296

P.S. PHPUnit failures return exit code is 1.
