### ISSUE TITLE
Subdirectories not used

### ISSUE THREAD

**Issue by philippgerard** [verkkokauppacom/parallel-phpunit#7]
When I use parallel-phpunit in my root test directory, only the BootstrapTest.php file which is located directly in the root directory is used. No subdirectory is analysed or used for a test-run.

Using phpunit, the subdirectories are used as expected.

```
parallel-phpunit . > 1 file tested
phpunit . > all files tested
```

My phpunit.xml isn't fancy at all.

```
<phpunit bootstrap="./bootstrap.php" colors="true"></phpunit>
```

Any hints as to why that happens?

Thanks!

Best,
Philipp

**Comment by razielsd** [comment]
xml config not supported. Try use shell script with options instead of xml config.

**Comment by siivonen** [comment]
If you manage to get your tests to work like this:

```
cd tests
phpunit dir1/MyTest.php
phpunit dir2/MySecondTest.php
```

you shouldn't have a problem anymore. You probably now have several phpunit.xml files and those won't work with parallel-phpunit since it executes several phpunit processes simultaneously and doesn't change the working directories.

We have one phpunit.xml in the root directory and we run the tests always from that directory. This way we can use both phpunit and parallel-phpunit freely.

**Comment by razielsd** [comment]
Better solution :)
parallel-phpunit -c full/path/phpunit.xml .

**Comment by philippgerard** [comment]
@siivonen We also use only one phpunit.xml in the root directory. I'll play around with it a little bit more on thursday and let you know if I can get it to work :)

**Comment by philippgerard** [comment]
I don't know what's wrong here, but despite the fact that we only use one phpunit.xml and even when I pass the path to the xml as @razielsd suggested, only one test is ever executed (the one located in the tests directory), but never any test in a subdirectory. Also, if I – instead of using "." to target the local directory – provide the path to a specific testfile in a subdirectory, the only output I get is the help-output, explaining me what paralleling options there are ;).

Any ideas? :)

``` bash
vagrant@vagrant-debian-squeeze-64:/vagrant/project/tests$ /vagrant/tools/parallel-phpunit/bin/parallel-phpunit .
Running parallel-phpunit 1.2
Starting command with thread 0: /usr/bin/phpunit -d parallel-phpunit-thread=0  ./BootstrapTest.php
Success: 0 Fail: 0 Error: 0 Skip: 0 Incomplete: 0
Success: 0 Fail: 0 Error: 0 Skip: 0 Incomplete: 0
Command ended: /usr/bin/phpunit -d parallel-phpunit-thread=0  ./BootstrapTest.php
PHPUnit 3.7.20 by Sebastian Bergmann.

Configuration read from /vagrant/project/tests/phpunit.xml

.......

Time: 3 seconds, Memory: 32.75Mb

OK (7 tests, 27 assertions)
Success: 7 Fail: 0 Error: 0 Skip: 0 Incomplete: 0
vagrant@vagrant-debian-squeeze-64:/vagrant/project/tests$ /vagrant/tools/parallel-phpunit/bin/parallel-phpunit application/models/Mail/MailHelperTest.php 
Running parallel-phpunit 1.2
Paralleling options:
    --pu-cmd - custom phpunit run script, default: first phpunit in PATH or phpunit next to parallel-phpunit
    --pu-threads - max threads, default 3
    --pu-retries - how many times to rerun the test file if it fails
Usage: parallel-phpunit [switches] <directory>
vagrant@vagrant-debian-squeeze-64:/vagrant/project/tests$ 
```

**Comment by razielsd** [comment]
Absolute path for phpunit.xml:

```
vagrant@vagrant-debian-squeeze-64:/vagrant/project/tests$ /vagrant/tools/parallel-phpunit/bin/parallel-phpunit -c /vagrant/project/tests/phpunit.xml .
```

**Comment by philippgerard** [comment]
Same effect.

**Comment by razielsd** [comment]
Use from phpunit.xml absolute path for bootstrap.

**Comment by siivonen** [comment]
@philippgerard 

In the first problem it seems that parallel-phpunit can find only one test file under the /vagrant/project/tests. The test files are searched using the 'find' command line from the given directory using the --test-suffix configuration ('Test.php,.phpt' by default). The files that are not matching the given --filter pattern are ignored.

You can run following command to check which find command will be used internally and to figure out why your test files are not found.

```
bash -x <your parallel-phpunit command> 2>&1 | grep find | head -1 
```

The second problem is caused by wrong command line. Parallel-phpunit can only parallelize test execution in test file level (not test method level). That's why you can give only test directory as command line parameter (not test file).

**Comment by philippgerard** [comment]
```
bash -x /vagrant/tools/parallel-phpunit/bin/parallel-phpunit 2>&1 | grep find | head -1
```

returns nothing at all ;-)

**Comment by siivonen** [comment]
There are parameters missing from your parallel-phpunit command. You should run for example:

```
bash -x /vagrant/tools/parallel-phpunit/bin/parallel-phpunit . 2>&1 | grep find | head -1
```

**Comment by philippgerard** [comment]
My bad :+1:

```
+++ find . -name BootstrapTest.php -o -name '*.phpt'
```

is the output of running the command you suggested. I get the same output no matter what folder I pass instead of the dot.

Thanks for your debugging help!

**Comment by siivonen** [comment]
Congratulations @philippgerard, you found a bug! Your BootstrapTest.php and wildcard expansion messed the test file search.

The bug should be fixed now in master. Please try if it works!

**Comment by philippgerard** [comment]
Now it works, thanks!

I'm relieved that it actually was a bug and not just me ;-)
